

spring:
  application:
    name: eureka-client123

server:
  port: 8089


eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8081/eureka/
      defaultZone: http://localhost:8080/eureka/
