#端口
server:
  port: 8080
  Integer
#配置
spring:
  shardingsphere:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      names: shard_order_0,shard_order_1
      shard_order_0:

        url:
        username: root
        password: 123456
      shard_order_1:
        url:
        username: root
        password: 123456
    props:
      sql:
        show: true  #显示sql
    sharding:
      tables:
        orders:
          actualDataNodes: shard_order_$->{0..1}.orders_$->{0..1}
          databaseStrategy:
            inline:
              shardingColumn:  addDate
          tableStrategy:
            inline:
              shardingColumn: id
        orders_detail:
          actualDataNodes: shard_order_$->{0..1}.orders_detail_$->{0..1}
          tableStrategy:
            inline:
              shardingColumn: orders_id
  devtools:
    restart:
      enabled: false



