mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8099


logging:
  config: classpath:log/logback.xml
spring:
  redis:
    database: 0
    host: 39.104.159.18
    port: 6379
    password: lichao.5220246
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
    timeout: 100
